### ISSUE TITLE
[Bug] Hook not shooting due to game language setting

### ISSUE THREAD

**Issue by cancercatalyst** [Elephant-Studios/WandasGizmos#13]
## Describe The Bug*
The grappling hook does not shoot when the game language is set to Russian. Switching it to English fixes the issue.

## To Reproduce*
1. Set the game language setting to Russian
2. Throw the hook
3. The hook does not shoot

## Versions*
 - Game: 1.19.8
 - Mod: 1.0.1

## Additional Context
Have not tried reproducing the issue with other game language setting variants, they might be broken too.

**Comment by Desymoo** [comment]
Already fixed by PR #12, should hopefully have the update out soon. Thank you for the report :)
